name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        hello: [AAA, CCC, EEE]
        include:
          - hello: AAA
            bye: BBB
          - hello: CCC
            key: DDD
          - hello: EEE
            bye: FFF
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo HELLO ${{matrix.hello}} and BYE ${{matrix.bye}}
