name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix: 
        hello: [AAA, CCC, EEE]
        include:
          - hello: AAA
            bye: BBB
            wait: true
          - hello: CCC
            key: DDD
          - hello: EEE
            bye: FFF
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo HELLO ${{matrix.hello}} and BYE ${{matrix.bye}}
        
    - name: Wait
      if: matrix.wait
      run: sleep 20
      
    - name: Run again
      run: echo HELLO ${{matrix.hello}} and BYE ${{matrix.bye}}
